### PR TITLE
add vitalpoint node to testnet-clay

### PR DESCRIPTION
**Pull request by ALuhning**
Have setup a node on an Azure VM.  Request it be added to the peerlist.

### CODE REVIEW

**Comment by v-stickykeys** [comment]
We haven't decided on concrete expectations for the nodes in the peerlist but at least one thing that should be true is:

1. Your multiaddress should not change. (If it needs to, it should **very rarely** change). Otherwise nodes connecting to your multiaddress will log noisy errors, and this list will become unpredictable which we hope to avoid.

Given that you've listed an ipv4 I want to confirm that this is a persistent address for your node but additionally I'd recommend putting this behind dns instead in the event you need to make changes that result in this address changing.

It's also up to discussion if we should require dns. @oed thoughts?

Also worth mentioning that across your own nodes you can configure a Ceramic IPFS node with a custom peerlist. See here:

**Comment by ALuhning** [comment]
Have added dns.

My next question may not inspire confidence :), but my intent is to keep this node online and running reliably.  To that end, I'm wondering if someone could point me to how to configure the VM (Ubuntu 20) to start and run the ceramic daemon automatically on failure/reboot should that ever occur. 

Have tried a couple things so far with not much success. - will figure it out, but if anyone wants to help speed me along, would appreciate it.

**Comment by v-stickykeys** [comment]
> Have tried a couple things so far with not much success. - will figure it out, but if anyone wants to help speed me along, would appreciate it.
@ALuhning 

Have you tried systemd? I haven't set this up myself but should be straightforward. https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd

The thing you really want to ensure is that your `./ceramic` directory does not get deleted. You might consider an external volume or optionally keeping the whole thing in S3 (which is what we do for now).

**Comment by ALuhning** [comment]
Thanks for that.  Happy to report that that redundancy is now working.  Daemon gets restarted if there is an issue or VM restarts.  The node should be accessible/reliable.  Working great for us.

Currently have the .ceramic directory on the OS disk.  If I was to move it to an external volume - how would I go about telling the daemon to save it's info there?

**Comment by v-stickykeys** [comment]
> Currently have the .ceramic directory on the OS disk. If I was to move it to an external volume - how would I go about telling the daemon to save it's info there?

Ah my previous comment should have been more clear.

Must save:

- IPFS directory (holds data created by the Ceramic node and all configuration that allows other nodes to communicate with yours)

Should save:

- Ceramic state store (holds pinned streams)

When the volume is mounted at its mount point (e.g. `/mnt/vol1`) you can use that path as inputs for the IPFS node and the Ceramic node.

For IPFS you want to set the `IPFS_PATH` to something like `/mnt/vol1/ipfs`
https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/ipfs-daemon/src/ipfs-daemon.ts#L63

For Ceramic you can set the `--state-store-directory` to something like `/mnt/vol1/ceramic-statestore`

**Comment by ALuhning** [comment]
Thanks, I had actually managed to figure it out, but that confirms I did it right. Node has been running continuously without issue for couple weeks now.

**Review by v-stickykeys — CHANGES_REQUESTED** [review]
@ALuhning Can you confirm that your peer id is still accurate?

I am getting errors when attempting to swarm connect

```
swarm connecting to /dns4/ceramic-node.vitalpointai.com/tcp/4012/ws/p2p/QmWanQaChJ4yeBfQtpqvSJCYYH9g35YnY2ViiXfKbyu1yE
swarm connect failed 
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
```

**Comment by ALuhning** [comment]
Closing this - after switching back to the clay testnet, it seems the performance issues I had been seeing that initially propelled me to run my own node are now solved.  May come back to this at some point, but for now the ceramic nodes are working very well for what we need.  Will be shutting down this node for the time being.

**Pull request closed without merging**
