### PR TITLE
Add bulla network to peerlist

### PR DESCRIPTION
**Pull request by bengobeil**
## Team:
Bulla Network
My discord handle is bengobeil#0300

## Use case:
We are using Ceramic to store contacts on our invoicing protocol. Assigning name and email address to a wallet address.

## Overview:
We are running the Ceramic node in AWS using the terraform module. IPFS out of process

We are using s3 buckets for persistence.

Here is my peerId from AWS logs:

image

Here is my Route 53 record:

image

### CODE REVIEW

**Comment by bengobeil** [comment]
I don't see my address in the logs (success or fail), is there something I am missing?

**Comment by bengobeil** [comment]
Stand by... dns stuff to do

**Comment by smrz2001** [comment]
Thanks, @bengobeil!

Will still need your static IP address before we can merge this.

**Comment by bengobeil** [comment]
Hi @smrz2001, given the Terraform deployment strategy, is the static IP you are looking for referring to the elastic IP I assigned to the VPC?

**Comment by bengobeil** [comment]
I mostly ask this question, because in the context of destroying/reapplying, not sure if I have any configuration to statically set IPs for the load balancers

**Comment by smrz2001** [comment]
Hey @bengobeil, since you're using the terraform module, we're looking for the static IP address of your Fargate instance. This is the node that communicates with our anchor service and that must thus be allowed through the anchor service firewall.

Here's a reference article about achieving this:
https://aws.amazon.com/premiumsupport/knowledge-center/ecs-fargate-static-elastic-ip-address/

Let me know if you have any more questions.

**Comment by bengobeil** [comment]
@smrz2001 hmm... it seems my tasks are running but I don't have a designated ECS instance for my Fargate tasks. 

According to your link, I do have an elastic IP for outbound traffic that I configured for my VPC. it is: 54.163.72.187

Let me know if this is what you are looking for, or if I need to configure an additional Network Load Balancer in addition to the application load balancer that is setup by Terraform

**Comment by smrz2001** [comment]
Yeah, unfortunately, you'll need to add the NLB as well :(

We're working on a more hands-off, permission-less model, so please bear with us till we get that sorted out. I understand that it's a bit of a pain to setting this up currently.

**Comment by bengobeil** [comment]
@smrz2001 

Ok no worries, which tcp ports does this load balancer need to listen on and what protocol? (assuming it is TCP but making sure)

**Comment by smrz2001** [comment]
@bengobeil 

Since this is the _outbound_ IP address your node will be using to communicate with the CAS, you'll need to follow this step from the article:

> To create a static IP address for a Fargate task for outbound traffic, [create a NAT gateway](https://aws.amazon.com/premiumsupport/knowledge-center/nat-gateway-vpc-private-subnet/). In this scenario, a static IP address is required by the downstream consumer. You must place your Fargate task on a private subnet. You can use the NAT gateway IP address for an IP allow list.

You shouldn't need to configure the protocol/port in this case.

**Comment by bengobeil** [comment]
Ok, well in that case, it seems that was already configured, and it is the IP address I mentioned above: 54.163.72.187

**Comment by bengobeil** [comment]
You must have added the IP address at about 2:30 PM EST because the node has not crashed since then, and health checks are passing!

image

**Comment by bengobeil** [comment]
Don't merge yet! I want to change the domain name, now that I know it is supposed to be ipfs and not ceramic! Will notify when ready.

**Comment by smrz2001** [comment]
Ok, sounds good, @bengobeil. Will wait for your confirmation!

**Comment by bengobeil** [comment]
image
Hmm something wrong with my certificate?

@smrz2001

**Comment by smrz2001** [comment]
Hmm, good question, @bengobeil.

How is your certificate provisioned? Also, mind trying with `ws` instead of `wss` in your entry?

e.g. `/dns4/ipfs.bulla.network/tcp/4012/ws/p2p/QmZEBCCTLLgcRhWi2D9cH77HGNXKoA2QpXKhrRvJnH4Y4w`

**Comment by bengobeil** [comment]
image
ayyyyyyyyyy we got it!!! ready to merge on my end! @smrz2001

**Comment by smrz2001** [comment]
Done @bengobeil!

**Comment by bengobeil** [comment]
Thanks for the support @smrz2001!

**Pull request merged**
